config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :logins
  resources :student
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
	has_many :students
	has_one :teacher
	validates :Password, presence: true,
                    length: { minimum: 5 }
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def create
	  @login = Login.new(params[:new_login])
	 
		if @login.save
	     redirect_to root_url, :notice => "Signed up!"
	    else
	      render "new"
	    end
	end

	def new 
	end
	
	private
	  def login_params
	    params.require(:login).permit(:username, :Password)
	  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
	def create
	  @login = Login.new(params[:new_login])
	 
		if @login.save
	     redirect_to root_url, :notice => "Signed up!"
	    else
	      render "new"
	    end
	end

	def new 
	end
	
	private
	  def login_params
	    params.require(:login).permit(:username, :Password)
	  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SRMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/index.html.erb
<center>

<h1> LOGIN </h1>
<%= form_with model: @login, local: true do |form| %>
<p>
<%= form.label :Username %><br>
<%= form.text_field :Username %>
</p>

<p>
<%= form.label :Password %><br>
<%= form.text_field :Password %>
</p>
<p>
    <%= form.submit %>
  </p>
<% end %>

app/views/logins/new.html.erb
<center>
<h1>
<%= link_to 'Teacher', new_teacher_path %><br>

<%= link_to 'Back', welcome_index_path %></h1>

app/views/student/new.html.erb
<center>

<h1> LOGIN </h1>
<%= form_with model: @login, local: true do |form| %>
<p>
<%= form.label :Username %><br>
<%= form.text_field :Username %>
</p>

<p>
<%= form.label :Password %><br>
<%= form.text_field :Password %>
</p>
<p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', welcome_index_path %></h1>

app/views/teacher/new.html.erb
<center>

<h1> LOGIN </h1>
<%= form_with model: @login, local: true do |form| %>
<p>
<%= form.label :Username %><br>
<%= form.text_field :Username %>
</p>

<p>
<%= form.label :Password %><br>
<%= form.text_field :Password %>
</p>
<p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', welcome_index_path %></h1>

app/views/welcome/index.html.erb
<center> <h1>Welcome to Student Result Management System</h1> 
	<%= image_tag("harry.jpg", {:style => "width:700px;"}) %><br>
<%= link_to 'Click here to Continue', new_login_path %>